version: '3.8'

services:
  invoice-tracker:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    volumes:
      - ./incoming_invoices:/app/incoming_invoices
      - ./processed_invoices:/app/processed_invoices
      - ./data:/app/data
      - ./logs:/app/logs
      - ./exports:/app/exports
    restart: unless-stopped

  # Optional: Add a database service for production
  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: invoice_tracker
  #     POSTGRES_USER: tracker_user
  #     POSTGRES_PASSWORD: secure_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
